# Generated by Django 4.0.4 on 2022-07-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('up_since', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
