# Generated by Django 4.0.6 on 2022-07-29 06:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_chat_alter_productd_options_delete_review'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Chatr',
        ),
    ]
