# Generated by Django 4.0.6 on 2022-07-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_chat_chatr'),
    ]

    operations = [
        migrations.AddField(
            model_name='productd',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Chatr',
        ),
    ]
