# Generated by Django 4.0.6 on 2022-08-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_chatr_productt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatr',
            old_name='productt',
            new_name='chad',
        ),
    ]
