# Generated by Django 4.0.6 on 2022-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_chatr_owner_alter_chatr_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatr',
            name='customer',
            field=models.TextField(null=True),
        ),
    ]
