# Generated by Django 4.0.6 on 2022-08-02 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_chatr_customerr_alter_chatr_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatr',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='chatr',
            name='customerr',
        ),
        migrations.AddField(
            model_name='chatr',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
