# Generated by Django 4.0.6 on 2022-08-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_chatr_customer_remove_chatr_customerr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatr',
            old_name='owner',
            new_name='customerr',
        ),
    ]
