# Generated by Django 4.0.6 on 2022-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_owner_chatr_customerr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatr',
            old_name='customerr',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='chatr',
            name='customer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
