# Generated by Django 4.0.6 on 2022-08-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_owner_chatr_chat_user_remove_chatr_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatr',
            old_name='chad',
            new_name='chadd',
        ),
    ]
